#!/bin/csh

# default variable
set BASEPATH=/disk/tio/tmp

if ("$1" != "") then
    set BASEPATH="$BASEPATH/$1"
    echo "${0}: BASEPATH=$BASEPATH"
endif

set OUTDIR=out_HiCARS1
mkdir -p $OUTDIR

# Unfoc.py currently doesn't work, because it doesn't recognize RADjh1 format yet.

time python2.7 ../unfoc.py \
    --infile $WAIS/orig/xlob/ASB/JKB1a/Y38a/RADjh1/bxds1 \
    --channel_def "[1,1,1,0,0;2,2,1,0,0]" \
    --output_samples 3200 \
    --outdir $OUTDIR \
    --output_phases \
    --StackDepth 10 \
    --IncoDepth 5 \
    --Scale 20000 \
    --blanking 50
    #--debug
    #--SweepLength 3200 \
    #--InputCT $WAIS/orig/xlob/ASB/JKB1a/Y38a/RADjh1/ct.gz \
    #--InputName $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/bxds \
    #--InputCT $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/ct.gz \
