#!/bin/csh

set BASEPATH=/disk/tio/tmp

if ("$1" != "") then
    set BASEPATH="$BASEPATH/$1"
    echo "${0}: BASEPATH=$BASEPATH"
endif

set OUTDIR=test_RADnh3_MARFA
mkdir -p $OUTDIR



time python2.7 ../unfoc.py \
    --infile $WAIS/orig/xlob/MBL/MKB2l/Y76a/RADnh3/bxds \
    --channel_def 2 \
    --output_samples 3200 \
    --outdir $OUTDIR \
    --StackDepth 10 \
    --IncoDepth 5 \
    --Scale 20000 \
    --bandpass \
    --output_phases \
    --blanking 200 
    #--InputName $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/bxds \
    #--InputCT $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/ct.gz \
