#!/bin/csh

# default variable
set BASEPATH=/disk/tio/tmp

time python2.7 unfoc.py \
    --InputName $WAIS/orig/xlob/ASB/JKB1a/Y38a/RADjh1/bxds \
    --InputCT $WAIS/orig/xlob/ASB/JKB1a/Y38a/RADjh1/ct.gz \
    --ChannelNum "[1,1,1,0,0;2,2,1,0,0]" \
    --SweepLength 3200 \
    --truncSweepLength 3200 \
    --MagName MagH1.out \
    --MetaName MetaH1.out \
    --StackDepth 10 \
    --IncoDepth 5 \
    --CenterMult 10 \
    --MaxDepth 150 \
    --Scale 20000 \
        --StartSamp 1 \
        --EndSamp 3200 \
    --basepath $BASEPATH \
    --blanking 50 --StreamName RADjh1
    #--InputName $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/bxds \
    #--InputCT $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/ct.gz \
