#!/bin/csh

time python2.7 unfoc.py \
    --infile $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/bxds \
    --channel_def 2 \
    --output_samples 3200 \
    --outdir . \
    --StackDepth 10 \
    --IncoDepth 5 \
    --Scale 20000 \
    --blanking 200
    #--InputName $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/bxds \
    #--InputCT $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/ct.gz \
