#!/bin/csh

set BASEPATH=/disk/tio/tmp

time python2.7 unfocused_radar_processer.py \
    --InputName $WAIS/orig/xlob/MBL/MKB2l/Y76a/RADnh3/bxds \
    --InputCT $WAIS/orig/xlob/MBL/MKB2l/Y76a/RADnh3/ct.gz \
    --ChannelNum 2 \
    --SweepLength 3437 \
    --truncSweepLength 3200 \
    --MagName Mag.out \
    --PhsName Phs.out \
    --MetaName Meta.out \
    --StackDepth 10 \
    --IncoDepth 5 \
    --CenterMult 10 \
    --MaxDepth 150 \
    --Scale 20000 \
        --StartSamp 1 \
        --EndSamp 3437 \
    --basepath $BASEPATH \
    --BandpassSamplingMode \
    --blanking 200 --StreamName RADnh3
    #--InputName $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/bxds \
    #--InputCT $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/ct.gz \
