#!/bin/csh

set BASEPATH=/disk/tio/tmp

if ("$1" != "") then
    set BASEPATH="$BASEPATH/$1"
    echo "${0}: BASEPATH=$BASEPATH"
endif


time python2.7 unfoc.py \
    --InputName $WAIS/orig/xlob/MBL/MKB2l/Y76a/RADnh3/bxds \
    --InputCT $WAIS/orig/xlob/MBL/MKB2l/Y76a/RADnh3/ct.gz \
    --ChannelNum 2 \
    --SweepLength 3437 \
    --truncSweepLength 3200 \
    --MagName Mag.out \
    --PhsName Phs.out \
    --MetaName Meta.out \
    --StackDepth 10 \
    --IncoDepth 5 \
    --CenterMult 10 \
    --MaxDepth 150 \
    --Scale 20000 \
        --StartSamp 1 \
        --EndSamp 3437 \
    --basepath $BASEPATH \
    --BandpassSamplingMode \
    --blanking 200 --StreamName RADnh3 \
    --progress \
    --debug
    #--InputName $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/bxds \
    #--InputCT $WAIS/orig/xlob/MBL/JKB2h/Y90a/RADnh3/ct.gz \
